<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-BR" xml:lang="pt-BR"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Igor e Lucas">

<title>Estudo de regressão linear</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Índice</h2>
   
  <ul>
  <li><a href="#introdução" id="toc-introdução" class="nav-link active" data-scroll-target="#introdução"><span class="header-section-number">1</span> Introdução</a></li>
  <li><a href="#objetivos" id="toc-objetivos" class="nav-link" data-scroll-target="#objetivos"><span class="header-section-number">2</span> Objetivos</a>
  <ul class="collapse">
  <li><a href="#objetivo-geral" id="toc-objetivo-geral" class="nav-link" data-scroll-target="#objetivo-geral"><span class="header-section-number">2.1</span> Objetivo Geral</a></li>
  <li><a href="#objetivos-específicos" id="toc-objetivos-específicos" class="nav-link" data-scroll-target="#objetivos-específicos"><span class="header-section-number">2.2</span> Objetivos Específicos</a></li>
  </ul></li>
  <li><a href="#metodologia" id="toc-metodologia" class="nav-link" data-scroll-target="#metodologia"><span class="header-section-number">3</span> Metodologia</a></li>
  <li><a href="#fundamentação-teórica" id="toc-fundamentação-teórica" class="nav-link" data-scroll-target="#fundamentação-teórica"><span class="header-section-number">4</span> Fundamentação Teórica</a>
  <ul class="collapse">
  <li><a href="#regressão-linear" id="toc-regressão-linear" class="nav-link" data-scroll-target="#regressão-linear"><span class="header-section-number">4.1</span> Regressão Linear</a></li>
  <li><a href="#variável-explicativa" id="toc-variável-explicativa" class="nav-link" data-scroll-target="#variável-explicativa"><span class="header-section-number">4.2</span> Variável Explicativa</a></li>
  <li><a href="#variável-resposta" id="toc-variável-resposta" class="nav-link" data-scroll-target="#variável-resposta"><span class="header-section-number">4.3</span> Variável Resposta</a></li>
  <li><a href="#coeficiente-angular" id="toc-coeficiente-angular" class="nav-link" data-scroll-target="#coeficiente-angular"><span class="header-section-number">4.4</span> Coeficiente Angular</a></li>
  <li><a href="#coeficiente-de-determinação" id="toc-coeficiente-de-determinação" class="nav-link" data-scroll-target="#coeficiente-de-determinação"><span class="header-section-number">4.5</span> Coeficiente de Determinação</a></li>
  <li><a href="#como-a-regressão-se-relaciona-com-a-engenharia-mecatrônica" id="toc-como-a-regressão-se-relaciona-com-a-engenharia-mecatrônica" class="nav-link" data-scroll-target="#como-a-regressão-se-relaciona-com-a-engenharia-mecatrônica"><span class="header-section-number">4.6</span> Como a regressão se relaciona com a Engenharia Mecatrônica</a></li>
  </ul></li>
  <li><a href="#resultados-obtidos-no-experimento" id="toc-resultados-obtidos-no-experimento" class="nav-link" data-scroll-target="#resultados-obtidos-no-experimento"><span class="header-section-number">5</span> Resultados Obtidos no Experimento</a></li>
  <li><a href="#aplicação-no-r" id="toc-aplicação-no-r" class="nav-link" data-scroll-target="#aplicação-no-r"><span class="header-section-number">6</span> Aplicação no R</a>
  <ul class="collapse">
  <li><a href="#dados" id="toc-dados" class="nav-link" data-scroll-target="#dados"><span class="header-section-number">6.1</span> Dados</a></li>
  <li><a href="#tabelas-das-médias" id="toc-tabelas-das-médias" class="nav-link" data-scroll-target="#tabelas-das-médias"><span class="header-section-number">6.2</span> Tabelas das médias</a></li>
  <li><a href="#gráfico" id="toc-gráfico" class="nav-link" data-scroll-target="#gráfico"><span class="header-section-number">6.3</span> Gráfico</a></li>
  </ul></li>
  <li><a href="#discussão-dos-resultados" id="toc-discussão-dos-resultados" class="nav-link" data-scroll-target="#discussão-dos-resultados"><span class="header-section-number">7</span> Discussão dos resultados</a></li>
  <li><a href="#conclusão" id="toc-conclusão" class="nav-link" data-scroll-target="#conclusão"><span class="header-section-number">8</span> Conclusão</a></li>
  <li><a href="#referências" id="toc-referências" class="nav-link" data-scroll-target="#referências"><span class="header-section-number">9</span> Referências</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">
<div class="logos" style="display: flex; justify-content: center; align-items: center; height: 200px; gap: 20px;">

  <a href="https://ufsj.edu.br">

    <img src="imagens/ufsj.png" width="220px">

  </a>

  <a href="https://ufsj.edu.br/defim">

    <img src="imagens/defim.png" width="220px">

  </a>

</div>

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Estudo de regressão linear</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Código</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Mostrar o código</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Esconder o código</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">Ver o código fonte</a></li></ul></div></div>
<p class="subtitle lead"><a href="https://bendeivide.github.io/courses/epaec/" target="_blank">Estatística e Probabilidade</a> <br> <a href="https://bendeivide.github.io" target="_blank">Prof.&nbsp;Ben Dêivide (DEFIM/CAP/UFSJ)</a></p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor</div>
    <div class="quarto-title-meta-contents">
             <p>Igor e Lucas </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Data de Publicação</div>
    <div class="quarto-title-meta-contents">
      <p class="date">3 de julho de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introdução" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introdução"><span class="header-section-number">1</span> Introdução</h2>
<p>A regressão linear é uma ferramenta muito utilizada na estatística para estudar a relação entre duas variáveis quantitativas. Neste relatório, foi analisada a distância percorrida por uma bolinhas lançada por uma catapulta em relação aos diferentes ângulos de lançamento. O experimento busca compreender como à variação do ângulo da catapulta pode infulenciar o alcance da bolinha e qual das configuração produz a maior distância.</p>
</section>
<section id="objetivos" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="objetivos"><span class="header-section-number">2</span> Objetivos</h2>
<section id="objetivo-geral" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="objetivo-geral"><span class="header-section-number">2.1</span> Objetivo Geral</h3>
<p>Estudar a relação entre o ângulo de lançamento e a distância percorrida pela bolinha utilizando técnicas de regressão.</p>
</section>
<section id="objetivos-específicos" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="objetivos-específicos"><span class="header-section-number">2.2</span> Objetivos Específicos</h3>
<ul>
<li>Coletar dados experimentais da catapulta.</li>
<li>Ajustar um modelo de regressão.</li>
<li>Avaliar a influência do ângulo na distância percorrida.<br>
</li>
<li>Identificar o ângulo associado ao maior alcance.</li>
</ul>
</section>
</section>
<section id="metodologia" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metodologia"><span class="header-section-number">3</span> Metodologia</h2>
<p>O experimento foi realizado utilizando um catapulta configurada com os níveis <span class="math inline">\(O^-= 2\)</span>, <span class="math inline">\(A^+=1\)</span>, <span class="math inline">\(A^-=2\)</span>. Para o valor <span class="math inline">\(B^+\)</span>(ângulo de lançamento) foi utilizado nove graus de inclinação distintos, para cada nível foi realizado dois lançamentos, totalizando dezoito observações.</p>
<p>A distância foi medida tomando como referência o tamanho do piso a uma distância de 1,12m da catapulta. Os desvios observados em centímetros foram convertidos para metros como e utilizados como variável resposta.</p>
<p>Para a análise estatística foi utilizado a linguagem R, ajustando-se um modelo de regressão entre o ângulo de lançamento e a distância percorrida.</p>
</section>
<section id="fundamentação-teórica" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="fundamentação-teórica"><span class="header-section-number">4</span> Fundamentação Teórica</h2>
<section id="regressão-linear" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="regressão-linear"><span class="header-section-number">4.1</span> Regressão Linear</h3>
<p>É um modelo estatístico utilizado para modelar a relação entre duas variáveis através de uma função linear. Estatisticamentem o objetivo é estimar os parâmetros de uma reta que minimize a soma dos quadrados dos resíduos, técnica conhecida como Método dos Mínimos Quadrados.</p>
</section>
<section id="variável-explicativa" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="variável-explicativa"><span class="header-section-number">4.2</span> Variável Explicativa</h3>
<p>Esta variável é utilizada para explicar a variação na variável resposta. Em um modelo de regressão, assume-se que ela não possui erro aleatório e que é controlada pelo pesquisador. No gráfico, ela ocupa o eixo das abscissas (X).</p>
</section>
<section id="variável-resposta" class="level3" data-number="4.3">
<h3 data-number="4.3" class="anchored" data-anchor-id="variável-resposta"><span class="header-section-number">4.3</span> Variável Resposta</h3>
<p>É a variável que se deseja estudar ou analisar. Ela contém um comportamento aleatório (erro) e sua variação, pode ser explicada pelas mudanças na variável explicativa. No gráfico, ela ocupa o eixo das coordenadas (Y).</p>
</section>
<section id="coeficiente-angular" class="level3" data-number="4.4">
<h3 data-number="4.4" class="anchored" data-anchor-id="coeficiente-angular"><span class="header-section-number">4.4</span> Coeficiente Angular</h3>
<p>O coeficiente angular representa a estimativa da variação média na variável resposta para cada unidade de aumento na variável explicativa. Ele indica a inclinação da reta e a direção da relação (positiva ou negativa).</p>
</section>
<section id="coeficiente-de-determinação" class="level3" data-number="4.5">
<h3 data-number="4.5" class="anchored" data-anchor-id="coeficiente-de-determinação"><span class="header-section-number">4.5</span> Coeficiente de Determinação</h3>
<p>É uma medida de ajuste que indica a proporção da variância da variável resposta que é explicada pelo modelo linear. Este coeficiente varia de 0 a 1.</p>
<p>Exemplo: Um <span class="math inline">\(R^2\)</span>= 0,98 indica que 98% da variabilidade dos dados de Y é explicada pela relação linear com X, sendo basicamente um indicador global do ajuste do modelo.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="componentes_regressao_linear.png" class="img-fluid figure-img"></p>
<figcaption>Imagem explicativa de como as variáveis se localizam</figcaption>
</figure>
</div>
<p>Através da imagem, é possível compreender como cada variável se organiza no gráfico de uma função linear. Da fórmula: <span class="math inline">\(Y = β_0+β_1X+ε\)</span></p>
</section>
<section id="como-a-regressão-se-relaciona-com-a-engenharia-mecatrônica" class="level3" data-number="4.6">
<h3 data-number="4.6" class="anchored" data-anchor-id="como-a-regressão-se-relaciona-com-a-engenharia-mecatrônica"><span class="header-section-number">4.6</span> Como a regressão se relaciona com a Engenharia Mecatrônica</h3>
<p>Na Engenharia Mecatrônica, a regressão linear é fundamental para:</p>
<ul>
<li><strong>Calibração de Sensores</strong>: Todo sensor mecatrônico (um sensor de pressão, um termistor ou um encoder) gera um sinal elétrico (Volts, mA) que precisa ser convertido em uma unidade física (Pascal,°C, Graus).</li>
</ul>
<p>Exemplo: O engenheiro coleta vários pontos de dados (Tensão vs Temperatura real). Através da regressão linear, encontra-se a equação que converte o sinal elétrico na medida real. Sem essa informação, o robô ou sistema não entenderia o que está recebendo.</p>
<ul>
<li><strong>Modelagem de Sistemas Dinâmicos</strong>: Geralmente, é preciso prever como um motor ou um braço robótico vai se mover.</li>
</ul>
<p>Exemplo: A relação entre a Corrente (A) enviada para um motor e o Torque (Nm) gerado é, em grande parte, linear. Usa-se a regressão linear para identificar as constantes do motor (como a constante de torque <span class="math inline">\(K_t\)</span>). Isso permite que o código de controle saiba quanto de energia enviar para obter o movimento desejado.</p>
<ul>
<li><strong>Robótica e Machine Learning</strong>: A regressão linear é peça fundamental para a Inteligência Artificial. Muitos algoritmos de decisão em robôs começam com regressões simples para entender padrões de movimento ou de consumo de energia. É a base para algoritmos mais complexos como os de redes neurais.</li>
</ul>
</section>
</section>
<section id="resultados-obtidos-no-experimento" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="resultados-obtidos-no-experimento"><span class="header-section-number">5</span> Resultados Obtidos no Experimento</h2>
<p>Na tabela abaixo, são representados os valores obtidos experimentalmente para diferentes graus de lançamento da catapulta.Foi utilizado o valor de 1,12 m como referência para a medição do alcance da bolinha, sendo os resultados expressos em relação a essa referência.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Ângulo (°)</th>
<th style="text-align: center;">Repetição 1 (m)</th>
<th style="text-align: center;">Repetição 2 (m)</th>
<th style="text-align: center;">Médias (m)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">80</td>
<td style="text-align: center;">1,17</td>
<td style="text-align: center;">1,19</td>
<td style="text-align: center;">1,18</td>
</tr>
<tr class="even">
<td style="text-align: center;">90</td>
<td style="text-align: center;">1,15</td>
<td style="text-align: center;">1,31</td>
<td style="text-align: center;">1,23</td>
</tr>
<tr class="odd">
<td style="text-align: center;">100</td>
<td style="text-align: center;">1,44</td>
<td style="text-align: center;">1,22</td>
<td style="text-align: center;">1,33</td>
</tr>
<tr class="even">
<td style="text-align: center;">110</td>
<td style="text-align: center;">1,31</td>
<td style="text-align: center;">1,07</td>
<td style="text-align: center;">1,19</td>
</tr>
<tr class="odd">
<td style="text-align: center;">120</td>
<td style="text-align: center;">0,90</td>
<td style="text-align: center;">0,85</td>
<td style="text-align: center;">0,87</td>
</tr>
<tr class="even">
<td style="text-align: center;">130</td>
<td style="text-align: center;">1,54</td>
<td style="text-align: center;">1,46</td>
<td style="text-align: center;">1,50</td>
</tr>
<tr class="odd">
<td style="text-align: center;">140</td>
<td style="text-align: center;">0,97</td>
<td style="text-align: center;">0,90</td>
<td style="text-align: center;">0,93</td>
</tr>
<tr class="even">
<td style="text-align: center;">150</td>
<td style="text-align: center;">0,44</td>
<td style="text-align: center;">0,51</td>
<td style="text-align: center;">0,47</td>
</tr>
</tbody>
</table>
</section>
<section id="aplicação-no-r" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="aplicação-no-r"><span class="header-section-number">6</span> Aplicação no R</h2>
<section id="dados" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="dados"><span class="header-section-number">6.1</span> Dados</h3>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cria um vetor chamado "angulo" com os valores dos ângulos testados no experimento.</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Cada ângulo aparece duas vezes porque foram realizadas duas repetições para cada condição.</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>angulo <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="dv">80</span>,<span class="dv">80</span>,</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="dv">90</span>,<span class="dv">90</span>,</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="dv">100</span>,<span class="dv">100</span>,</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="dv">110</span>,<span class="dv">110</span>,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="dv">120</span>,<span class="dv">120</span>,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="dv">130</span>,<span class="dv">130</span>,</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="dv">140</span>,<span class="dv">140</span>,</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  <span class="dv">150</span>,<span class="dv">150</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Cria um vetor chamado "distancia" com as distâncias percorridas pela bolinha, em metros.</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co"># A ordem dos valores deve corresponder à ordem dos ângulos no vetor anterior.</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>distancia <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>  <span class="fl">1.17</span>,<span class="fl">1.19</span>,</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>  <span class="fl">1.155</span>,<span class="fl">1.31</span>,</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>  <span class="fl">1.44</span>,<span class="fl">1.22</span>,</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>  <span class="fl">1.31</span>,<span class="fl">1.07</span>,</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>  <span class="fl">0.90</span>,<span class="fl">0.85</span>,</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>  <span class="fl">1.54</span>,<span class="fl">1.46</span>,</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>  <span class="fl">0.97</span>,<span class="fl">0.90</span>,</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>  <span class="fl">0.44</span>,<span class="fl">0.51</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Organiza os vetores em uma tabela de dados.</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="co"># A função data.frame() cria uma estrutura com linhas e colunas,</span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="co"># facilitando a análise estatística no R.</span></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>dados <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(angulo, distancia)</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Exibe a tabela criada para conferência dos dados inseridos.</span></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>dados</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   angulo distancia
1      80     1.170
2      80     1.190
3      90     1.155
4      90     1.310
5     100     1.440
6     100     1.220
7     110     1.310
8     110     1.070
9     120     0.900
10    120     0.850
11    130     1.540
12    130     1.460
13    140     0.970
14    140     0.900
15    150     0.440
16    150     0.510</code></pre>
</div>
</div>
</section>
<section id="tabelas-das-médias" class="level3" data-number="6.2">
<h3 data-number="6.2" class="anchored" data-anchor-id="tabelas-das-médias"><span class="header-section-number">6.2</span> Tabelas das médias</h3>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcula a média da distância para cada ângulo testado.</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># A expressão distancia ~ angulo indica que a distância será agrupada por ângulo.</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co"># O argumento data = dados informa que as variáveis estão no data frame "dados".</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># A função mean calcula a média das repetições em cada grupo.</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>medias <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(distancia <span class="sc">~</span> angulo,</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>                    <span class="at">data =</span> dados,</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>                    mean)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Exibe a tabela com a média da distância para cada ângulo.</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>medias</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  angulo distancia
1     80    1.1800
2     90    1.2325
3    100    1.3300
4    110    1.1900
5    120    0.8750
6    130    1.5000
7    140    0.9350
8    150    0.4750</code></pre>
</div>
</div>
</section>
<section id="gráfico" class="level3" data-number="6.3">
<h3 data-number="6.3" class="anchored" data-anchor-id="gráfico"><span class="header-section-number">6.3</span> Gráfico</h3>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajusta um modelo de regressão linear simples.</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co"># A função lm() estima uma reta que relaciona a variável distancia com a variável angulo.</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co"># A expressão distancia ~ angulo significa que a distância será explicada pelo ângulo.</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(distancia <span class="sc">~</span> angulo, <span class="at">data =</span> dados)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Exibe o resumo estatístico do modelo ajustado.</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="co"># O summary() mostra os coeficientes da reta, o valor de R² e outras informações do ajuste.</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = distancia ~ angulo, data = dados)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.39021 -0.16417 -0.03055  0.09505  0.56152 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1.942262   0.348381   5.575 6.84e-05 ***
angulo      -0.007414   0.002971  -2.495   0.0257 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2723 on 14 degrees of freedom
Multiple R-squared:  0.3078,    Adjusted R-squared:  0.2584 
F-statistic: 6.227 on 1 and 14 DF,  p-value: 0.0257</code></pre>
</div>
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Constrói um gráfico de dispersão com os dados experimentais.</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co"># O eixo X representa o ângulo de lançamento e o eixo Y representa a distância percorrida.</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  dados<span class="sc">$</span>angulo,</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  dados<span class="sc">$</span>distancia,</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">pch =</span> <span class="dv">19</span>,</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Ângulo (graus)"</span>,</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Distância (m)"</span>,</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">"Regressão Linear: Distância x Ângulo"</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Adiciona ao gráfico a reta de regressão estimada pelo modelo.</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co"># O argumento lwd = 2 aumenta a espessura da linha.</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># O argumento col = "red" destaca visualmente a reta ajustada.</span></span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>A função lm() é a principal função usada para ajustar a regressão linear no R. Ela calcula a equação da reta que melhor representa a relação entre as variáveis, de acordo com o método dos mínimos quadrados. A função summary() permite avaliar os resultados numéricos do modelo, como os coeficientes da reta e o coeficiente de determinação. A função plot() constrói o gráfico de dispersão, mostrando cada lançamento como um ponto. O argumento pch = 19 define pontos preenchidos, enquanto xlab, ylab e main definem os textos dos eixos e do título. Por fim, abline() adiciona a reta de regressão sobre os pontos, facilitando a visualização da tendência estimada.</p>
<p>Com os dados apresentados, o modelo linear estimado é aproximadamente:</p>
<p>distância = 1,9423 - 0,0074 * ângulo</p>
</section>
</section>
<section id="discussão-dos-resultados" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="discussão-dos-resultados"><span class="header-section-number">7</span> Discussão dos resultados</h2>
<p>A análise dos dados mostra que a distância percorrida pela bolinha variou de forma considerável conforme o ângulo de lançamento da catapulta. Observando as médias, o maior alcance ocorreu no ângulo de 130°, com média de aproximadamente 1,50 m. Em seguida, aparecem os ângulos de 100°, com média de 1,33 m, e 90°, com média aproximada de 1,23 m. O menor resultado foi observado em 150°, com média de aproximadamente 0,47 m.</p>
<p>Apesar de a regressão linear ajustada apresentar coeficiente angular negativo, indicando uma tendência geral de redução da distância conforme o ângulo aumenta, essa reta não explica completamente o comportamento observado. O coeficiente de determinação foi aproximadamente R² = 0,308, o que significa que cerca de 30,8% da variação da distância foi explicada pelo ângulo por meio de uma relação linear. Esse valor indica um ajuste limitado, pois grande parte da variação dos dados ainda permanece associada a outros fatores ou a um comportamento não linear.</p>
<p>Esse resultado é coerente com a natureza do experimento. Em lançamentos por catapulta, o alcance pode depender não apenas do ângulo, mas também da força aplicada, da posição inicial da bolinha, do atrito, da repetibilidade do mecanismo, da altura de lançamento e de pequenas diferenças no momento de liberação. Além disso, teoricamente, movimentos de projéteis costumam apresentar comportamento curvilíneo em relação ao ângulo, e não necessariamente uma relação em linha reta. Também é possível observar variações entre repetições de um mesmo ângulo. Por exemplo, em 100° foram registradas distâncias de 1,44 m e 1,22 m, enquanto em 110° foram obtidas distâncias de 1,31 m e 1,07 m. Essas diferenças mostram que o experimento possui variabilidade prática e que duas repetições por ângulo podem não ser suficientes para representar com grande precisão o comportamento médio de cada configuração.</p>
<p>Portanto, a regressão linear foi útil para fornecer uma primeira leitura estatística da relação entre ângulo e distância, mas os resultados sugerem que o fenômeno não é bem descrito apenas por uma reta. Para estudos futuros, seria interessante aumentar o número de repetições por ângulo e testar também um modelo de regressão quadrática, capaz de representar melhor a existência de um ponto de máximo alcance.</p>
</section>
<section id="conclusão" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="conclusão"><span class="header-section-number">8</span> Conclusão</h2>
<p>Com base nos dados coletados, foi possível aplicar a regressão linear para investigar a relação entre o ângulo de lançamento da catapulta e a distância percorrida pela bolinha. O modelo ajustado indicou uma tendência linear negativa, sugerindo que, em média, maiores ângulos estariam associados a menores distâncias. No entanto, essa tendência deve ser interpretada com cautela, pois o maior alcance médio foi observado em 130°, demonstrando que o comportamento experimental não segue uma relação estritamente linear.</p>
<p>O coeficiente de determinação de aproximadamente 30,8% mostra que o ângulo explica apenas parte da variação observada na distância. Isso indica que outros fatores experimentais também influenciaram os resultados, como a regularidade do lançamento, a força da catapulta, a posição da bolinha e possíveis erros de medição.</p>
<p>Assim, conclui-se que a regressão linear contribuiu para organizar e interpretar os dados experimentais, mas não foi suficiente para representar completamente o comportamento do alcance da bolinha. O ângulo de 130° foi o que apresentou melhor desempenho médio no experimento, enquanto uma análise mais aprofundada, com mais repetições e modelos não lineares, poderia fornecer uma representação mais precisa do fenômeno estudado.</p>
</section>
<section id="referências" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="referências"><span class="header-section-number">9</span> Referências</h2>
<p>[1] BATISTA, Ben Deivide. Livro de Estatística. Universidade Federal de São João del-Rei, UFSJ.</p>
<p>[2] MORETTIN, Pedro Alberto; BUSSAB, Wilton de Oliveira. Estatística básica. 9. ed.&nbsp;São Paulo: Saraiva, 2017.</p>
<!-- -->

</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Código fonte</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Só mude aqui!!!!</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Igor e Lucas"</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Estudo de regressão linear"</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="an">bibliography:</span><span class="co"> referencias.bib</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="co"># A partir daqui nao faca alteracoes!!!!!</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="an">link-citations:</span><span class="co"> true</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="an">csl:</span><span class="co"> associacao-brasileira-de-normas-tecnicas-ipea.csl</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="an">subtitle:</span><span class="co"> "&lt;a href='https://bendeivide.github.io/courses/epaec/' target='_blank'&gt;Estatística e Probabilidade&lt;/a&gt; &lt;/br&gt; &lt;a href='https://bendeivide.github.io' target='_blank'&gt;Prof. Ben Dêivide (DEFIM/CAP/UFSJ)&lt;/a&gt;"</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="an">include-before-body:</span><span class="co"> header.html</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> 07/03/2026</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a><span class="an">lang:</span><span class="co"> pt-BR</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a><span class="co">    number-sections: true</span></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a><span class="co">    theme: bootstrap</span></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a><span class="co">    #css: styles.css</span></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a><span class="an">execute:</span></span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a><span class="co">  echo: true</span></span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a><span class="co">  warning: false</span></span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a><span class="co">  message: false</span></span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a><span class="fu">## Introdução</span></span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a>A regressão linear é uma ferramenta muito utilizada na estatística para estudar a relação entre duas variáveis quantitativas. Neste relatório, foi analisada a distância percorrida por uma bolinhas lançada por uma catapulta em relação aos diferentes ângulos de lançamento. O experimento busca compreender como à variação do ângulo da catapulta pode infulenciar o alcance da bolinha e qual das configuração produz a maior distância.</span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a><span class="fu">## Objetivos </span></span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a><span class="fu">### Objetivo Geral</span></span>
<span id="cb9-35"><a href="#cb9-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-36"><a href="#cb9-36" aria-hidden="true" tabindex="-1"></a>Estudar a relação entre o ângulo de lançamento e a distância percorrida pela bolinha utilizando técnicas de regressão.</span>
<span id="cb9-37"><a href="#cb9-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-38"><a href="#cb9-38" aria-hidden="true" tabindex="-1"></a><span class="fu">### Objetivos Específicos </span></span>
<span id="cb9-39"><a href="#cb9-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-40"><a href="#cb9-40" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Coletar dados experimentais da catapulta.</span>
<span id="cb9-41"><a href="#cb9-41" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Ajustar um modelo de regressão.</span>
<span id="cb9-42"><a href="#cb9-42" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Avaliar a influência do ângulo na distância percorrida.  </span>
<span id="cb9-43"><a href="#cb9-43" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Identificar o ângulo associado ao maior alcance.</span>
<span id="cb9-44"><a href="#cb9-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-45"><a href="#cb9-45" aria-hidden="true" tabindex="-1"></a><span class="fu">## Metodologia </span></span>
<span id="cb9-46"><a href="#cb9-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-47"><a href="#cb9-47" aria-hidden="true" tabindex="-1"></a>O experimento foi realizado utilizando um catapulta configurada com os níveis $O^-= 2$, $A^+=1$, $A^-=2$. Para o valor $B^+$(ângulo de lançamento) foi utilizado nove graus de inclinação distintos, para cada nível foi realizado dois lançamentos, totalizando dezoito observações.</span>
<span id="cb9-48"><a href="#cb9-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-49"><a href="#cb9-49" aria-hidden="true" tabindex="-1"></a>A distância foi medida tomando como referência o tamanho do piso a uma distância de 1,12m da catapulta. Os desvios observados em centímetros foram convertidos para metros como e utilizados como variável resposta.  </span>
<span id="cb9-50"><a href="#cb9-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-51"><a href="#cb9-51" aria-hidden="true" tabindex="-1"></a>Para a análise estatística foi utilizado a linguagem R, ajustando-se um modelo de regressão entre o ângulo de lançamento e a distância percorrida.</span>
<span id="cb9-52"><a href="#cb9-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-53"><a href="#cb9-53" aria-hidden="true" tabindex="-1"></a><span class="fu">## Fundamentação Teórica</span></span>
<span id="cb9-54"><a href="#cb9-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-55"><a href="#cb9-55" aria-hidden="true" tabindex="-1"></a><span class="fu">### Regressão Linear </span></span>
<span id="cb9-56"><a href="#cb9-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-57"><a href="#cb9-57" aria-hidden="true" tabindex="-1"></a>É um modelo estatístico utilizado para modelar a relação entre duas variáveis através de uma função linear. Estatisticamentem o objetivo é estimar os parâmetros de uma reta que minimize a soma dos quadrados dos resíduos, técnica conhecida como Método dos Mínimos Quadrados.</span>
<span id="cb9-58"><a href="#cb9-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-59"><a href="#cb9-59" aria-hidden="true" tabindex="-1"></a><span class="fu">### Variável Explicativa</span></span>
<span id="cb9-60"><a href="#cb9-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-61"><a href="#cb9-61" aria-hidden="true" tabindex="-1"></a>Esta variável é utilizada para explicar a variação na variável resposta. Em um modelo de regressão, assume-se que ela não possui erro aleatório e que é controlada pelo pesquisador. No gráfico, ela ocupa o eixo das abscissas (X).</span>
<span id="cb9-62"><a href="#cb9-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-63"><a href="#cb9-63" aria-hidden="true" tabindex="-1"></a><span class="fu">### Variável Resposta</span></span>
<span id="cb9-64"><a href="#cb9-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-65"><a href="#cb9-65" aria-hidden="true" tabindex="-1"></a>É a variável que se deseja estudar ou analisar. Ela contém um comportamento aleatório (erro) e sua variação, pode ser explicada  pelas mudanças na variável explicativa. No gráfico, ela ocupa o eixo das coordenadas (Y).</span>
<span id="cb9-66"><a href="#cb9-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-67"><a href="#cb9-67" aria-hidden="true" tabindex="-1"></a><span class="fu">### Coeficiente Angular</span></span>
<span id="cb9-68"><a href="#cb9-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-69"><a href="#cb9-69" aria-hidden="true" tabindex="-1"></a>O coeficiente angular representa a estimativa da variação média na variável resposta para cada unidade de aumento na variável explicativa. Ele indica a inclinação da reta e a direção da relação (positiva ou negativa).</span>
<span id="cb9-70"><a href="#cb9-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-71"><a href="#cb9-71" aria-hidden="true" tabindex="-1"></a><span class="fu">### Coeficiente de Determinação</span></span>
<span id="cb9-72"><a href="#cb9-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-73"><a href="#cb9-73" aria-hidden="true" tabindex="-1"></a>É uma medida de ajuste que indica a proporção da variância da variável resposta que é explicada pelo modelo linear. Este coeficiente varia de 0 a 1. </span>
<span id="cb9-74"><a href="#cb9-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-75"><a href="#cb9-75" aria-hidden="true" tabindex="-1"></a>Exemplo: Um $R^2$= 0,98 indica que 98% da variabilidade dos dados de Y é explicada pela relação linear com X, sendo basicamente um indicador global do ajuste do modelo.</span>
<span id="cb9-76"><a href="#cb9-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-77"><a href="#cb9-77" aria-hidden="true" tabindex="-1"></a><span class="al">![Imagem explicativa de como as variáveis se localizam](componentes_regressao_linear.png)</span></span>
<span id="cb9-78"><a href="#cb9-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-79"><a href="#cb9-79" aria-hidden="true" tabindex="-1"></a>Através da imagem, é possível compreender como cada variável se organiza no gráfico de uma função linear. Da fórmula: $Y = β_0+β_1X+ε$  </span>
<span id="cb9-80"><a href="#cb9-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-81"><a href="#cb9-81" aria-hidden="true" tabindex="-1"></a><span class="fu">### Como a regressão se relaciona com a Engenharia Mecatrônica</span></span>
<span id="cb9-82"><a href="#cb9-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-83"><a href="#cb9-83" aria-hidden="true" tabindex="-1"></a>Na Engenharia Mecatrônica, a regressão linear é fundamental para:</span>
<span id="cb9-84"><a href="#cb9-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-85"><a href="#cb9-85" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Calibração de Sensores**: Todo sensor mecatrônico (um sensor de pressão, um termistor ou um encoder) gera um sinal elétrico (Volts, mA) que precisa ser convertido em uma unidade física (Pascal,°C, Graus).  </span>
<span id="cb9-86"><a href="#cb9-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-87"><a href="#cb9-87" aria-hidden="true" tabindex="-1"></a>Exemplo: O engenheiro coleta vários pontos de dados (Tensão vs Temperatura real). Através da regressão linear, encontra-se a equação que converte o sinal elétrico na medida real. Sem essa informação, o robô ou sistema não entenderia o que está recebendo.</span>
<span id="cb9-88"><a href="#cb9-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-89"><a href="#cb9-89" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Modelagem de Sistemas Dinâmicos**: Geralmente, é preciso prever como um motor ou um braço robótico vai se mover. </span>
<span id="cb9-90"><a href="#cb9-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-91"><a href="#cb9-91" aria-hidden="true" tabindex="-1"></a>Exemplo: A relação entre a Corrente (A) enviada para um motor e o Torque (Nm) gerado é, em grande parte, linear. Usa-se a regressão linear para identificar as constantes do motor (como a constante de torque $K_t$). Isso permite que o código de controle saiba quanto de energia enviar para obter o movimento desejado.</span>
<span id="cb9-92"><a href="#cb9-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-93"><a href="#cb9-93" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Robótica e Machine Learning**: A regressão linear é peça fundamental para a Inteligência Artificial. Muitos algoritmos de decisão em robôs começam com regressões simples para entender padrões de movimento ou de consumo de energia. É a base para algoritmos mais complexos como os de redes neurais.</span>
<span id="cb9-94"><a href="#cb9-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-95"><a href="#cb9-95" aria-hidden="true" tabindex="-1"></a><span class="fu">## Resultados Obtidos no Experimento</span></span>
<span id="cb9-96"><a href="#cb9-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-97"><a href="#cb9-97" aria-hidden="true" tabindex="-1"></a>Na tabela abaixo, são representados os valores obtidos experimentalmente para diferentes graus de lançamento da catapulta.Foi utilizado o valor de 1,12 m como referência para a medição do alcance da bolinha, sendo os resultados expressos em relação a essa referência.</span>
<span id="cb9-98"><a href="#cb9-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-99"><a href="#cb9-99" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Ângulo (°) <span class="pp">|</span> Repetição 1 (m) <span class="pp">|</span> Repetição 2 (m) <span class="pp">|</span> Médias (m) <span class="pp">|</span> </span>
<span id="cb9-100"><a href="#cb9-100" aria-hidden="true" tabindex="-1"></a><span class="pp">| :--------:</span> <span class="pp">| :-------------:</span> <span class="pp">| :-------------:</span> <span class="pp">| :--------:</span> <span class="pp">|</span></span>
<span id="cb9-101"><a href="#cb9-101" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span>     80     <span class="pp">|</span>       1,17      <span class="pp">|</span>       1,19      <span class="pp">|</span>    1,18    <span class="pp">|</span>  </span>
<span id="cb9-102"><a href="#cb9-102" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span>     90     <span class="pp">|</span>       1,15      <span class="pp">|</span>       1,31      <span class="pp">|</span>    1,23    <span class="pp">|</span></span>
<span id="cb9-103"><a href="#cb9-103" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span>     100    <span class="pp">|</span>       1,44      <span class="pp">|</span>       1,22      <span class="pp">|</span>    1,33    <span class="pp">|</span></span>
<span id="cb9-104"><a href="#cb9-104" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span>     110    <span class="pp">|</span>       1,31      <span class="pp">|</span>       1,07      <span class="pp">|</span>    1,19    <span class="pp">|</span></span>
<span id="cb9-105"><a href="#cb9-105" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span>     120    <span class="pp">|</span>       0,90      <span class="pp">|</span>       0,85      <span class="pp">|</span>    0,87    <span class="pp">|</span></span>
<span id="cb9-106"><a href="#cb9-106" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span>     130    <span class="pp">|</span>       1,54      <span class="pp">|</span>       1,46      <span class="pp">|</span>    1,50    <span class="pp">|</span></span>
<span id="cb9-107"><a href="#cb9-107" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span>     140    <span class="pp">|</span>       0,97      <span class="pp">|</span>       0,90      <span class="pp">|</span>    0,93    <span class="pp">|</span></span>
<span id="cb9-108"><a href="#cb9-108" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span>     150    <span class="pp">|</span>       0,44      <span class="pp">|</span>       0,51      <span class="pp">|</span>    0,47    <span class="pp">|</span> </span>
<span id="cb9-109"><a href="#cb9-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-110"><a href="#cb9-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-111"><a href="#cb9-111" aria-hidden="true" tabindex="-1"></a><span class="fu">## Aplicação no R</span></span>
<span id="cb9-112"><a href="#cb9-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-113"><a href="#cb9-113" aria-hidden="true" tabindex="-1"></a><span class="fu">### Dados</span></span>
<span id="cb9-114"><a href="#cb9-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-117"><a href="#cb9-117" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb9-118"><a href="#cb9-118" aria-hidden="true" tabindex="-1"></a><span class="co"># Cria um vetor chamado "angulo" com os valores dos ângulos testados no experimento.</span></span>
<span id="cb9-119"><a href="#cb9-119" aria-hidden="true" tabindex="-1"></a><span class="co"># Cada ângulo aparece duas vezes porque foram realizadas duas repetições para cada condição.</span></span>
<span id="cb9-120"><a href="#cb9-120" aria-hidden="true" tabindex="-1"></a>angulo <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb9-121"><a href="#cb9-121" aria-hidden="true" tabindex="-1"></a>  <span class="dv">80</span>,<span class="dv">80</span>,</span>
<span id="cb9-122"><a href="#cb9-122" aria-hidden="true" tabindex="-1"></a>  <span class="dv">90</span>,<span class="dv">90</span>,</span>
<span id="cb9-123"><a href="#cb9-123" aria-hidden="true" tabindex="-1"></a>  <span class="dv">100</span>,<span class="dv">100</span>,</span>
<span id="cb9-124"><a href="#cb9-124" aria-hidden="true" tabindex="-1"></a>  <span class="dv">110</span>,<span class="dv">110</span>,</span>
<span id="cb9-125"><a href="#cb9-125" aria-hidden="true" tabindex="-1"></a>  <span class="dv">120</span>,<span class="dv">120</span>,</span>
<span id="cb9-126"><a href="#cb9-126" aria-hidden="true" tabindex="-1"></a>  <span class="dv">130</span>,<span class="dv">130</span>,</span>
<span id="cb9-127"><a href="#cb9-127" aria-hidden="true" tabindex="-1"></a>  <span class="dv">140</span>,<span class="dv">140</span>,</span>
<span id="cb9-128"><a href="#cb9-128" aria-hidden="true" tabindex="-1"></a>  <span class="dv">150</span>,<span class="dv">150</span></span>
<span id="cb9-129"><a href="#cb9-129" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-130"><a href="#cb9-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-131"><a href="#cb9-131" aria-hidden="true" tabindex="-1"></a><span class="co"># Cria um vetor chamado "distancia" com as distâncias percorridas pela bolinha, em metros.</span></span>
<span id="cb9-132"><a href="#cb9-132" aria-hidden="true" tabindex="-1"></a><span class="co"># A ordem dos valores deve corresponder à ordem dos ângulos no vetor anterior.</span></span>
<span id="cb9-133"><a href="#cb9-133" aria-hidden="true" tabindex="-1"></a>distancia <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb9-134"><a href="#cb9-134" aria-hidden="true" tabindex="-1"></a>  <span class="fl">1.17</span>,<span class="fl">1.19</span>,</span>
<span id="cb9-135"><a href="#cb9-135" aria-hidden="true" tabindex="-1"></a>  <span class="fl">1.155</span>,<span class="fl">1.31</span>,</span>
<span id="cb9-136"><a href="#cb9-136" aria-hidden="true" tabindex="-1"></a>  <span class="fl">1.44</span>,<span class="fl">1.22</span>,</span>
<span id="cb9-137"><a href="#cb9-137" aria-hidden="true" tabindex="-1"></a>  <span class="fl">1.31</span>,<span class="fl">1.07</span>,</span>
<span id="cb9-138"><a href="#cb9-138" aria-hidden="true" tabindex="-1"></a>  <span class="fl">0.90</span>,<span class="fl">0.85</span>,</span>
<span id="cb9-139"><a href="#cb9-139" aria-hidden="true" tabindex="-1"></a>  <span class="fl">1.54</span>,<span class="fl">1.46</span>,</span>
<span id="cb9-140"><a href="#cb9-140" aria-hidden="true" tabindex="-1"></a>  <span class="fl">0.97</span>,<span class="fl">0.90</span>,</span>
<span id="cb9-141"><a href="#cb9-141" aria-hidden="true" tabindex="-1"></a>  <span class="fl">0.44</span>,<span class="fl">0.51</span></span>
<span id="cb9-142"><a href="#cb9-142" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-143"><a href="#cb9-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-144"><a href="#cb9-144" aria-hidden="true" tabindex="-1"></a><span class="co"># Organiza os vetores em uma tabela de dados.</span></span>
<span id="cb9-145"><a href="#cb9-145" aria-hidden="true" tabindex="-1"></a><span class="co"># A função data.frame() cria uma estrutura com linhas e colunas,</span></span>
<span id="cb9-146"><a href="#cb9-146" aria-hidden="true" tabindex="-1"></a><span class="co"># facilitando a análise estatística no R.</span></span>
<span id="cb9-147"><a href="#cb9-147" aria-hidden="true" tabindex="-1"></a>dados <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(angulo, distancia)</span>
<span id="cb9-148"><a href="#cb9-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-149"><a href="#cb9-149" aria-hidden="true" tabindex="-1"></a><span class="co"># Exibe a tabela criada para conferência dos dados inseridos.</span></span>
<span id="cb9-150"><a href="#cb9-150" aria-hidden="true" tabindex="-1"></a>dados</span>
<span id="cb9-151"><a href="#cb9-151" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-152"><a href="#cb9-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-153"><a href="#cb9-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-154"><a href="#cb9-154" aria-hidden="true" tabindex="-1"></a><span class="fu">### Tabelas das médias</span></span>
<span id="cb9-155"><a href="#cb9-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-158"><a href="#cb9-158" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb9-159"><a href="#cb9-159" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcula a média da distância para cada ângulo testado.</span></span>
<span id="cb9-160"><a href="#cb9-160" aria-hidden="true" tabindex="-1"></a><span class="co"># A expressão distancia ~ angulo indica que a distância será agrupada por ângulo.</span></span>
<span id="cb9-161"><a href="#cb9-161" aria-hidden="true" tabindex="-1"></a><span class="co"># O argumento data = dados informa que as variáveis estão no data frame "dados".</span></span>
<span id="cb9-162"><a href="#cb9-162" aria-hidden="true" tabindex="-1"></a><span class="co"># A função mean calcula a média das repetições em cada grupo.</span></span>
<span id="cb9-163"><a href="#cb9-163" aria-hidden="true" tabindex="-1"></a>medias <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(distancia <span class="sc">~</span> angulo,</span>
<span id="cb9-164"><a href="#cb9-164" aria-hidden="true" tabindex="-1"></a>                    <span class="at">data =</span> dados,</span>
<span id="cb9-165"><a href="#cb9-165" aria-hidden="true" tabindex="-1"></a>                    mean)</span>
<span id="cb9-166"><a href="#cb9-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-167"><a href="#cb9-167" aria-hidden="true" tabindex="-1"></a><span class="co"># Exibe a tabela com a média da distância para cada ângulo.</span></span>
<span id="cb9-168"><a href="#cb9-168" aria-hidden="true" tabindex="-1"></a>medias</span>
<span id="cb9-169"><a href="#cb9-169" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-170"><a href="#cb9-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-171"><a href="#cb9-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-172"><a href="#cb9-172" aria-hidden="true" tabindex="-1"></a><span class="fu">### Gráfico</span></span>
<span id="cb9-173"><a href="#cb9-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-176"><a href="#cb9-176" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb9-177"><a href="#cb9-177" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajusta um modelo de regressão linear simples.</span></span>
<span id="cb9-178"><a href="#cb9-178" aria-hidden="true" tabindex="-1"></a><span class="co"># A função lm() estima uma reta que relaciona a variável distancia com a variável angulo.</span></span>
<span id="cb9-179"><a href="#cb9-179" aria-hidden="true" tabindex="-1"></a><span class="co"># A expressão distancia ~ angulo significa que a distância será explicada pelo ângulo.</span></span>
<span id="cb9-180"><a href="#cb9-180" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(distancia <span class="sc">~</span> angulo, <span class="at">data =</span> dados)</span>
<span id="cb9-181"><a href="#cb9-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-182"><a href="#cb9-182" aria-hidden="true" tabindex="-1"></a><span class="co"># Exibe o resumo estatístico do modelo ajustado.</span></span>
<span id="cb9-183"><a href="#cb9-183" aria-hidden="true" tabindex="-1"></a><span class="co"># O summary() mostra os coeficientes da reta, o valor de R² e outras informações do ajuste.</span></span>
<span id="cb9-184"><a href="#cb9-184" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo)</span>
<span id="cb9-185"><a href="#cb9-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-186"><a href="#cb9-186" aria-hidden="true" tabindex="-1"></a><span class="co"># Constrói um gráfico de dispersão com os dados experimentais.</span></span>
<span id="cb9-187"><a href="#cb9-187" aria-hidden="true" tabindex="-1"></a><span class="co"># O eixo X representa o ângulo de lançamento e o eixo Y representa a distância percorrida.</span></span>
<span id="cb9-188"><a href="#cb9-188" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb9-189"><a href="#cb9-189" aria-hidden="true" tabindex="-1"></a>  dados<span class="sc">$</span>angulo,</span>
<span id="cb9-190"><a href="#cb9-190" aria-hidden="true" tabindex="-1"></a>  dados<span class="sc">$</span>distancia,</span>
<span id="cb9-191"><a href="#cb9-191" aria-hidden="true" tabindex="-1"></a>  <span class="at">pch =</span> <span class="dv">19</span>,</span>
<span id="cb9-192"><a href="#cb9-192" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Ângulo (graus)"</span>,</span>
<span id="cb9-193"><a href="#cb9-193" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Distância (m)"</span>,</span>
<span id="cb9-194"><a href="#cb9-194" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">"Regressão Linear: Distância x Ângulo"</span></span>
<span id="cb9-195"><a href="#cb9-195" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-196"><a href="#cb9-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-197"><a href="#cb9-197" aria-hidden="true" tabindex="-1"></a><span class="co"># Adiciona ao gráfico a reta de regressão estimada pelo modelo.</span></span>
<span id="cb9-198"><a href="#cb9-198" aria-hidden="true" tabindex="-1"></a><span class="co"># O argumento lwd = 2 aumenta a espessura da linha.</span></span>
<span id="cb9-199"><a href="#cb9-199" aria-hidden="true" tabindex="-1"></a><span class="co"># O argumento col = "red" destaca visualmente a reta ajustada.</span></span>
<span id="cb9-200"><a href="#cb9-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-201"><a href="#cb9-201" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-202"><a href="#cb9-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-203"><a href="#cb9-203" aria-hidden="true" tabindex="-1"></a>A função lm() é a principal função usada para ajustar a regressão linear no R. Ela calcula a equação da reta que melhor representa a relação entre as variáveis, de acordo com o método dos mínimos quadrados. A função summary() permite avaliar os resultados numéricos do modelo, como os coeficientes da reta e o coeficiente de determinação. A função plot() constrói o gráfico de dispersão, mostrando cada lançamento como um ponto. O argumento pch = 19 define pontos preenchidos, enquanto xlab, ylab e main definem os textos dos eixos e do título. Por fim, abline() adiciona a reta de regressão sobre os pontos, facilitando a visualização da tendência estimada.</span>
<span id="cb9-204"><a href="#cb9-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-205"><a href="#cb9-205" aria-hidden="true" tabindex="-1"></a>Com os dados apresentados, o modelo linear estimado é aproximadamente:</span>
<span id="cb9-206"><a href="#cb9-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-207"><a href="#cb9-207" aria-hidden="true" tabindex="-1"></a>distância = 1,9423 - 0,0074 * ângulo</span>
<span id="cb9-208"><a href="#cb9-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-209"><a href="#cb9-209" aria-hidden="true" tabindex="-1"></a><span class="fu">## Discussão dos resultados</span></span>
<span id="cb9-210"><a href="#cb9-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-211"><a href="#cb9-211" aria-hidden="true" tabindex="-1"></a>A análise dos dados mostra que a distância percorrida pela bolinha variou de forma considerável conforme o ângulo de lançamento da catapulta. Observando as médias, o maior alcance ocorreu no ângulo de 130°, com média de aproximadamente 1,50 m. Em seguida, aparecem os ângulos de 100°, com média de 1,33 m, e 90°, com média aproximada de 1,23 m. O menor resultado foi observado em 150°, com média de aproximadamente 0,47 m.</span>
<span id="cb9-212"><a href="#cb9-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-213"><a href="#cb9-213" aria-hidden="true" tabindex="-1"></a>Apesar de a regressão linear ajustada apresentar coeficiente angular negativo, indicando uma tendência geral de redução da distância conforme o ângulo aumenta, essa reta não explica completamente o comportamento observado. O coeficiente de determinação foi aproximadamente R² = 0,308, o que significa que cerca de 30,8% da variação da distância foi explicada pelo ângulo por meio de uma relação linear. Esse valor indica um ajuste limitado, pois grande parte da variação dos dados ainda permanece associada a outros fatores ou a um comportamento não linear.</span>
<span id="cb9-214"><a href="#cb9-214" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-215"><a href="#cb9-215" aria-hidden="true" tabindex="-1"></a>Esse resultado é coerente com a natureza do experimento. Em lançamentos por catapulta, o alcance pode depender não apenas do ângulo, mas também da força aplicada, da posição inicial da bolinha, do atrito, da repetibilidade do mecanismo, da altura de lançamento e de pequenas diferenças no momento de liberação. Além disso, teoricamente, movimentos de projéteis costumam apresentar comportamento curvilíneo em relação ao ângulo, e não necessariamente uma relação em linha reta.</span>
<span id="cb9-216"><a href="#cb9-216" aria-hidden="true" tabindex="-1"></a>Também é possível observar variações entre repetições de um mesmo ângulo. Por exemplo, em 100° foram registradas distâncias de 1,44 m e 1,22 m, enquanto em 110° foram obtidas distâncias de 1,31 m e 1,07 m. Essas diferenças mostram que o experimento possui variabilidade prática e que duas repetições por ângulo podem não ser suficientes para representar com grande precisão o comportamento médio de cada configuração.</span>
<span id="cb9-217"><a href="#cb9-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-218"><a href="#cb9-218" aria-hidden="true" tabindex="-1"></a>Portanto, a regressão linear foi útil para fornecer uma primeira leitura estatística da relação entre ângulo e distância, mas os resultados sugerem que o fenômeno não é bem descrito apenas por uma reta. Para estudos futuros, seria interessante aumentar o número de repetições por ângulo e testar também um modelo de regressão quadrática, capaz de representar melhor a existência de um ponto de máximo alcance.</span>
<span id="cb9-219"><a href="#cb9-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-220"><a href="#cb9-220" aria-hidden="true" tabindex="-1"></a><span class="fu">## Conclusão</span></span>
<span id="cb9-221"><a href="#cb9-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-222"><a href="#cb9-222" aria-hidden="true" tabindex="-1"></a>Com base nos dados coletados, foi possível aplicar a regressão linear para investigar a relação entre o ângulo de lançamento da catapulta e a distância percorrida pela bolinha. O modelo ajustado indicou uma tendência linear negativa, sugerindo que, em média, maiores ângulos estariam associados a menores distâncias. No entanto, essa tendência deve ser interpretada com cautela, pois o maior alcance médio foi observado em 130°, demonstrando que o comportamento experimental não segue uma relação estritamente linear.</span>
<span id="cb9-223"><a href="#cb9-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-224"><a href="#cb9-224" aria-hidden="true" tabindex="-1"></a>O coeficiente de determinação de aproximadamente 30,8% mostra que o ângulo explica apenas parte da variação observada na distância. Isso indica que outros fatores experimentais também influenciaram os resultados, como a regularidade do lançamento, a força da catapulta, a posição da bolinha e possíveis erros de medição.</span>
<span id="cb9-225"><a href="#cb9-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-226"><a href="#cb9-226" aria-hidden="true" tabindex="-1"></a>Assim, conclui-se que a regressão linear contribuiu para organizar e interpretar os dados experimentais, mas não foi suficiente para representar completamente o comportamento do alcance da bolinha. O ângulo de 130° foi o que apresentou melhor desempenho médio no experimento, enquanto uma análise mais aprofundada, com mais repetições e modelos não lineares, poderia fornecer uma representação mais precisa do fenômeno estudado.</span>
<span id="cb9-227"><a href="#cb9-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-228"><a href="#cb9-228" aria-hidden="true" tabindex="-1"></a><span class="fu">## Referências</span></span>
<span id="cb9-229"><a href="#cb9-229" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">1</span><span class="co">]</span> BATISTA, Ben Deivide. Livro de Estatística. Universidade Federal de São João del-Rei, UFSJ.</span>
<span id="cb9-230"><a href="#cb9-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-231"><a href="#cb9-231" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">2</span><span class="co">]</span> MORETTIN, Pedro Alberto; BUSSAB, Wilton de Oliveira. Estatística básica. 9. ed. São Paulo: Saraiva, 2017.</span>
</code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>